---
# System Entity
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: default
  name: todo-system
  title: Todo System
  description: System managing the Todo application
spec:
  owner: user:guest

---
# Service Component Entity
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: todo-api
  title: Todo API Microservice
  description: Backend service for the Todo API built with Django REST Framework
  annotations:
    github.com/project-slug: Marlinekhavele/TODOAPI
spec:
  type: service
  owner: user:guest
  system: todo-system
  lifecycle: production
  providesApis:
    - todo-api
  dependsOn:
    - resource:default/todo 
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: todo
  title: Todo Database
  description: The database for the Todo API microservice
spec:
  type: database
  owner: user:guest
  system: todo-system
  lifecycle: production

---
# API Entity
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: default
  name: todo-api
  title: Todo API
  description: API for managing Todo items
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  system: todo-system
  definition: "https://github.com/Marlinekhavele/TODOAPI/blob/main/docs/openapi.json"



