#
# System Entity
#
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: todo-app
  name: todo-system
  title: Todo System
  description: System managing the Todo application
spec:
  owner: user:marlinekhavele

---
#
# Service Component Entity
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: todo-app
  name: todo-api
  title: Todo API Microservice
  description: Backend service for the Todo API built with Django REST Framework
  annotations:
    github.com/project-slug: Marlinekhavele/TODOAPI
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:marlinekhavele
  system: todo-system
  lifecycle: production
  providesApis:
    - todo-api
  dependsOn:
    - resource:todo-db

---
#
# Database Resource Entity
#
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: todo
  name: todo
  title: Todo API Database
  description: The database for the Todo API microservice
spec:
  type: database
  owner: user:marlinekhavele
  system: todo-system
  lifecycle: production

---
#
# API Entity
#
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: todo-app
  name: todo-api
  title: Todo API
  description: API for managing Todo items
spec:
  type: openapi
  lifecycle: production
  owner: user:marlinekhavele
  system: todo-system
  definition:
    $text: |
      {"openapi": "3.0.0", "info": {"title": "Todo API", "version": "1.0.0"}}
