apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-api
  description: A Todo API built with Django REST Framework
  annotations:
    github.com/project-slug: Marlinekhavele/TODOAPI
spec:
  type: service
  lifecycle: production
  owner: user:default/marlinekhavele  
  system: system:default/todo-system  
  providesApis:
    - api:default/todo-api        
