"""Added column title

Revision ID: 80c5e133437d
Revises: 4883c98b8cd5
Create Date: 2024-11-29 12:52:51.956830

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80c5e133437d"
down_revision: Union[str, None] = "4883c98b8cd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("title", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "title")
    # ### end Alembic commands ###
